### ISSUE TITLE
Switching to Edit mode is not kept if a page opens in a new tab/window

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#326] opened 2020-05-12 18:46 UTC
## Description 
Switching to Edit mode is not kept if a page opens in a new tab/window

### Steps to reproduce
1. run Edit env.
2. open Home page
3. Switch to Edit mode
4. in a new tab/window, open a page, e.g. /touts
### Expected result
Edit mode is in use

### Actual result
Preview mode is applied

### Environment

System:
OS: macOS High Sierra 10.13.4
CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
Yarn: 1.17.0 - /usr/local/bin/yarn
npm: 6.14.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
Languages:
Python: 2.7.10 - /usr/bin/python
Browsers:
Chrome: 81.0.4044.138
Safari: 11.1
npmGlobalPackages:
gatsby-cli: 2.8.29

### Affected Version
reproduced in [Master](https://github.com/johnsonandjohnson/Bodiless-JS/commit/e16e2995dd88e0aca7ec1fbd21586358d327accd)

**Comment by asiarheyeu** [comment] 2020-06-01 14:34
Per bug scrub:

- Confirmed as not a bug, but expected behaviour. Closing

**Closed by asiarheyeu** 2020-06-01 14:34 UTC
