### ISSUE TITLE
RTE: Swapping RTE with a link to a Simple RTE puts a linked text to a separate line.

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#876] opened 2021-02-22 16:05 UTC
## Description
RTE: Swapping RTE with a link to a Simple RTE puts a linked text to a separate line.

### Steps to reproduce:
1. in Edit env, open /flow-container/
2. switch to edit mode
3. in a FC, add Basic RTE (or Full RTE)
4. add some text in RTE
5. apply a couple of 'link' style in the text
6. swap the RTE to Simple RTE

### Actual result
the link style is lost but each previously linked piece of text moves to the separate lines
![Screen Shot 2021-02-22 at 10 58 13 AM](https://user-images.githubusercontent.com/3224040/108734042-0ab34200-74fd-11eb-82bd-a78e14ae2f1b.png)

### Expected result
the link is lost, but the text stays as one piece without breaking to the separate lines

reproduced in Master

**Comment by asiarheyeu** [comment] 2021-02-23 14:57
Confirmed as low priority, since Flow Container will support only 1 RTE. Closed as won't fix.

**Closed by asiarheyeu** 2021-02-23 14:57 UTC
Labels: bug
