### ISSUE TITLE
Local Context Menu doesn't show up if any form of Editor Menu buttons is open

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#406] opened 2020-06-28 23:34 UTC
## Description
Local Context Menu doesn't show up if any form of Editor Menu buttons is open

### Steps to reproduce
1. open Edit env, any page, e.g Home page
2. click Edit button to switch to Edit mode
3. open any form, e.g click '+ New Page' in Editor Menu
4. doesn't close the form and try to open any Local Context Menu, e.g. click Menu item, or click an image in a Tout

### Expected result
Local Context Menu opens and functions

### Actual result
Local Context Menu doesn't open

### Environment
System:
OS: macOS High Sierra 10.13.4
CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
Yarn: 1.17.0 - /usr/local/bin/yarn
npm: 6.14.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
Languages:
Python: 2.7.10 - /usr/bin/python
Browsers:
Chrome: 81.0.4044.138
Safari: 11.1
npmGlobalPackages:
gatsby-cli: 2.8.29

### Affected Version
reproduced in Master

**Comment by irkhodzka** [comment] 2022-02-03 15:09
closing as the issue is not reproducible anymore

**Closed by irkhodzka** 2022-02-03 15:09 UTC
Labels: bug, accepted
