### ISSUE TITLE
Burger menu icon overlays admin menu on test site

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#729] opened 2020-12-01 11:34 UTC
STR
1. Resize window on test site so that burger menu appears
2. Switch admin menu to right side of screen.

ER.
Admin menu is on top and hides  burger menu icon

AR.
Burger menu icon overlays admin menu.

![image](https://user-images.githubusercontent.com/480145/100735463-3c55ba80-339f-11eb-996c-a8ec436a4de4.png)

**Comment by asiarheyeu** [comment] 2020-12-01 15:01
Duplicate of 256. Closing as a duplicate

**Closed by asiarheyeu** 2020-12-01 15:01 UTC
Labels: bug
