### ISSUE TITLE
Able to collapse, non collapsible accordion via keyboard space key

### ISSUE THREAD

**Issue by AshuraHassan** [johnsonandjohnson/Bodiless-JS#1076] opened 2021-09-03 16:26 UTC
## Description

Non collapsible accordions are able to collapse via keyboard using space key

### Steps to reproduce

1. Goto to /accordion/ on Edit Env
2. Click edit icon
3. Move control to non collapsible accordion via keyboard using Tab key
4. Click space key 

### Expected result

Non collapsible accordion should not be collapsed by keyboard and mouse 

### Actual result

Non collapsible accordion are able to collapse by keyboard

### Environment

master

### Affected Version

master env

**Comment by TatsianaMiraniuk** [comment] 2021-09-13 19:26
this is a duplicate of #1008

**Comment by asiarheyeu** [comment] 2021-09-27 14:28
Bug scrub notes: reproducible in static mode as well

**Closed** 2022-06-24 15:18 UTC
Labels: bug, won't fix
