### ISSUE TITLE
[GAP]: Burger Menu: URL value is lost after swapping Tout to List submenu

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#692] opened 2020-11-16 17:54 UTC
**Steps to reproduce:**
1. Open /megamenu/ in Edit mode
2. Click a top Mega menu item
3. Click 'Sub' icon
4. Select Tout and click V
5. Fill in Title, Body, CTA and add a Link value in CTA.
6. Swap the submenu to List
7. open Burger Menu
8. expand the item

**Actual Results:**
The submenu item lost the URL.

**Expected Results:**
URL value is still available after swapping from Tout to List

**Comment by irkhodzka** [comment] 2022-02-03 14:47
Closing as the issue is not reproducible anymore.

**Closed by irkhodzka** 2022-02-03 14:47 UTC
Labels: bug
