### ISSUE TITLE
Filters missing on test site products page

### ISSUE THREAD

**Issue by dewen** [johnsonandjohnson/Bodiless-JS#1299] opened 2021-12-14 14:40 UTC
## Description

Filters are not displayed on products static page, while shown on edit site.

### Steps to reproduce

- Checkout `main` branch and run setup/start
   `npm run setup && npm run start`
- Open edit site products page: http://localhost:8005/products
- Add filters (tags)
- Build static site and serve: 
   `npm run build`
- Open product page on **desktop**: http://localhost:9000/products/

### Expected result

Added filters displayed on products page

### Actual result

Filters missing.

<img width="962" alt="filter-1" src="https://user-images.githubusercontent.com/1812250/146019451-6308ce89-b52b-406d-a242-504d860c7f67.png">
<img width="888" alt="filter-2" src="https://user-images.githubusercontent.com/1812250/146019467-9748654e-dab4-4c5a-951b-d41eb6ac21ab.png">

**Comment by TatsianaMiraniuk** [comment] 2022-01-19 00:41
this is a duplicate of #1068

**Closed** 2022-01-27 18:36 UTC
Labels: bug
